### ISSUE TITLE
Subprocesses call 'small' queue

### ISSUE THREAD

**Issue by gemmalangridge** [sanger-pathogens/Farm_blast#18]
I've installed farm_blast on our LSF cluster and used the -q flag to specify a queue name that exists here, but subprocesses in the code submit jobs to a 'small' queue, which we don't have so it throws exceptions. Could the -q flag be amended to apply to all queues submitted to?

$ farm_blast -q short-eth --act RP62A.fasta CH16_S36normalized_scaffolds.fasta 
small: No such queue. Job not submitted.
Traceback (most recent call last):
  File "/gpfs/home/bxj16cvu/.local/lib/python3.5/site-packages/farmpy/lsf.py", line 110, in run
    bsub_out = subprocess.check_output(cmd, shell=True).decode('utf-8')
  File "/gpfs/software/python/anaconda/4.2/anaconda3/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/gpfs/software/python/anaconda/4.2/anaconda3/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'bsub -q small -E 'test -e /gpfs/home/bxj16cvu' -o 02.run_array.sh.o -e 02.run_array.sh.e -J farm_blast:/gpfs/home/bxj16cvu/maite/Farm_blast.RP62A.fasta.CH16_S36normalized_scaffolds.fasta.blast_plus.blastn.out.start_array -w 'done(315514)' bash 02.run_array.sh' returned non-zero exit status 255
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "/gpfs/software/python/anaconda/4.2/anaconda3/bin/farm_blast", line 18, in <module>
    blast_pipeline.run()
  File "/gpfs/home/bxj16cvu/.local/lib/python3.5/site-packages/farm_blast/pipeline.py", line 313, in run
    self.start_array_job.run()
  File "/gpfs/home/bxj16cvu/.local/lib/python3.5/site-packages/farmpy/lsf.py", line 112, in run
    raise Error('Error in bsub call. I tried to run:\n' + str(self))
farmpy.lsf.Error: Error in bsub call. I tried to run:
bsub -q small -E 'test -e /gpfs/home/bxj16cvu' -o 02.run_array.sh.o -e 02.run_array.sh.e -J farm_blast:/gpfs/home/bxj16cvu/maite/Farm_blast.RP62A.fasta.CH16_S36normalized_scaffolds.fasta.blast_plus.blastn.out.start_array -w 'done(315514)' bash 02.run_array.sh

**Comment by TushabeJV** [comment]
Just got the same error, still figuring out how to fix it!
